"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Radio, AlertTriangle, ShieldCheck, Download, ClipboardCheck } from "lucide-react";
import { AIBriefing } from "@/lib/types";

interface BriefingPanelProps {
  briefing: AIBriefing;
  onDownloadPDF: () => void;
  isDownloadingPDF: boolean;
}

export default function BriefingPanel({ briefing, onDownloadPDF, isDownloadingPDF }: BriefingPanelProps) {
  const [activeTab, setActiveTab] = useState<"brief" | "response" | "resilience">("brief");
  const [copied, setCopied] = useState(false);

  const copyBriefToClipboard = () => {
    const textToCopy = `
AEGISAI CRISIS RESPONSE EXECUTIVE SUMMARY
------------------------------------------
${briefing.executiveBrief}

SITUATION SUMMARY:
${briefing.situationSummary}

PRIORITY ACTIONS:
${briefing.priorityActions.map((a, i) => `${i + 1}. ${a}`).join("\n")}

RECOVERY STRATEGY:
${briefing.recoveryStrategy}
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const tabs = [
    { id: "brief", label: "Executive Briefing", icon: FileText },
    { id: "response", label: "Operational Response", icon: Radio },
    { id: "resilience", label: "Rehab & Resilience", icon: ShieldCheck },
  ];

  return (
    <div className="flex flex-col rounded-2xl border border-gray-200 bg-white shadow-xs overflow-hidden">
      
      {/* Header Panel */}
      <div className="flex flex-col border-b border-gray-100 bg-gray-50/50 p-6 md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-gray-950 flex items-center gap-2">
            <span className="flex h-2.5 w-2.5 rounded-full bg-blue-600"></span>
            AI Executive Briefing
          </h2>
          <p className="text-xs font-medium text-gray-500 mt-1">Generated by AegisAI Crisis Core & Gemini Platform</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={copyBriefToClipboard}
            className="flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3.5 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 hover:text-gray-900 transition-all cursor-pointer"
          >
            <ClipboardCheck className={`h-4 w-4 ${copied ? "text-emerald-500" : "text-gray-500"}`} />
            {copied ? "Copied" : "Copy Brief"}
          </button>
          
          <button
            onClick={onDownloadPDF}
            disabled={isDownloadingPDF}
            className="flex items-center gap-1.5 rounded-lg bg-gray-950 hover:bg-gray-900 text-white px-3.5 py-2 text-xs font-semibold shadow-xs disabled:opacity-50 transition-all cursor-pointer"
          >
            <Download className="h-4 w-4" />
            {isDownloadingPDF ? "Compiling PDF..." : "Export McKinsey PDF"}
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-gray-100 bg-white px-4">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-2 border-b-2 px-4 py-3 text-xs font-semibold tracking-wide uppercase transition-all duration-200 cursor-pointer ${
                isActive
                  ? "border-gray-950 text-gray-950 font-bold"
                  : "border-transparent text-gray-500 hover:text-gray-800"
              }`}
            >
              <Icon className="h-4 w-4" />
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Content Area */}
      <div className="p-6 bg-white min-h-[380px]">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -5 }}
            transition={{ duration: 0.15 }}
          >
            {activeTab === "brief" && (
              <div className="space-y-6">
                
                {/* McKinsey Highlight Box */}
                <div className="rounded-xl border border-blue-100 bg-blue-50/30 p-5 leading-relaxed">
                  <span className="text-[10px] font-bold text-blue-600 uppercase tracking-widest block mb-1">Brief Summary</span>
                  <p className="text-sm font-semibold text-gray-800 leading-relaxed italic">
                    "{briefing.executiveBrief}"
                  </p>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Situation Analysis</h3>
                  <p className="text-sm text-gray-700 leading-relaxed">{briefing.situationSummary}</p>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Immediate Priority Actions</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                    {briefing.priorityActions.map((action, i) => (
                      <div key={i} className="flex gap-3 rounded-lg border border-gray-100 bg-gray-50/50 p-4">
                        <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md bg-gray-950 text-xs font-bold text-white">
                          {i + 1}
                        </div>
                        <p className="text-xs text-gray-700 font-medium leading-normal">{action}</p>
                      </div>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Key Critical Risks</h3>
                  <ul className="space-y-2">
                    {briefing.keyRisks.map((risk, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-xs text-gray-700 font-medium">
                        <AlertTriangle className="h-4.5 w-4.5 text-amber-500 shrink-0 mt-0.5" />
                        <span>{risk}</span>
                      </li>
                    ))}
                  </ul>
                </div>

              </div>
            )}

            {activeTab === "response" && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Recommended Response Strategy</h3>
                  <div className="space-y-3">
                    {briefing.recommendedResponse.map((step, i) => (
                      <div key={i} className="flex gap-4 items-start p-4 rounded-xl border border-gray-100 bg-gray-50/50">
                        <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-50 text-blue-600 font-bold text-sm shrink-0">
                          {i + 1}
                        </div>
                        <div>
                          <p className="text-xs font-bold text-gray-900">Phase {i + 1} Deployments</p>
                          <p className="text-xs text-gray-600 mt-1 leading-relaxed">{step}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Stakeholder Coordination Plan</h3>
                  <div className="divide-y divide-gray-100 rounded-xl border border-gray-100 overflow-hidden bg-white">
                    {briefing.stakeholderCoordination.map((coordination, i) => {
                      const [agency, role] = coordination.includes(":") 
                        ? coordination.split(":") 
                        : [coordination, "Lead response operations coordination roles."];
                      return (
                        <div key={i} className="p-4 flex flex-col md:flex-row md:items-center gap-2">
                          <span className="text-xs font-bold text-gray-900 md:w-1/3 shrink-0">{agency}</span>
                          <span className="text-xs text-gray-600">{role.trim()}</span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {activeTab === "resilience" && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Recovery Strategy</h3>
                  <p className="text-sm text-gray-700 leading-relaxed p-4 rounded-xl border border-gray-100 bg-gray-50/50">
                    {briefing.recoveryStrategy}
                  </p>
                </div>

                <div>
                  <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2.5">Long-Term Resilience Recommendations</h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {briefing.longTermResilience.map((rec, i) => (
                      <div key={i} className="flex flex-col justify-between p-4 rounded-xl border border-gray-100 bg-white shadow-xs">
                        <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-widest">Resilience policy {i + 1}</span>
                        <p className="text-xs text-gray-700 font-medium leading-relaxed mt-2">{rec}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        </AnimatePresence>
      </div>

    </div>
  );
}
